# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guests', models.IntegerField(default=1)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('voc_trip', models.BooleanField(default=False, help_text='VOC trips are free.')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(help_text='Email address. Used to modify booking, so keep secret.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price as decimal number, eg. 19.23', max_digits=4)),
                ('capacity', models.PositiveIntegerField(help_text='Recommended capacity.')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.Guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.Hut'),
        ),
    ]
