# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0002_booking_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price as decimal number, eg. 19.23', max_digits=4)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='uuid_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.Booking'),
        ),
    ]
