# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0003_auto_20170429_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='uuid_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
