# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0004_auto_20170503_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
