# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200, null=True)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
