# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='date',
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
