# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20170303_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
